# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  dependencies:
    dir: .
    deps:
      - go-exists
      - install-lint-deps

  go-exists:
    preconditions:
      - which go

  install-lint-deps:
    status:
      - which golangci-lint
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.1
  
  test:
    dir: .
    deps:
      - dependencies
    cmds:
      - go test -cover ./...

  lint:
    dir: .
    deps:
      - dependencies
    cmds:
      - golangci-lint run --config=.golangci.yml

  lint-fix:
    dir: .
    deps:
      - dependencies
    cmds:
      - golangci-lint run --config=.golangci.yml --disable-all -E gofumpt --fix
      - golangci-lint run --config=.golangci.yml --fix

  build:
    dir: .
    deps:
      - dependencies
    cmds:
      - go mod tidy
      - go build -o simulator

  demo:
    dir: .
    deps:
      - build
    cmds:
      - ./simulator -c example/basic/config.yaml -t example/basic/3-3-square.xml -tr example/basic/traffic.csv -a -log

  demo-2:
    dir: .
    deps:
      - build
    cmds:
      - ./simulator -c example/high-load/config.yaml -t example/high-load/3-3-square.xml -tr example/high-load/traffic.csv -a -log

  mpb:
    dir: .
    deps:
      - build
    cmds:
      - ./simulator -c example/xiong-et-al-2017/config.yaml -t example/xiong-et-al-2017/5-node-line.xml -tr example/xiong-et-al-2017/traffic.csv -a -log

  mpb-2:
    dir: .
    deps:
      - build
    cmds:
      - ./simulator -c example/xiong-et-al-2016/config.yaml -t example/xiong-et-al-2016/7-node-line.xml -tr example/xiong-et-al-2016/traffic.csv -a -log